[project]
name = "bisindoapp"
version = "1.0.0"
description = "Aplikasi Bisindo AI"
requires-python = ">=3.10"
dependencies = [
    "tensorflow-cpu==2.12.0",
    "opencv-python-headless",
    "pillow",
    "imutils",
    "mediapipe",
    "pytz",
    "Flask",
    "gunicorn"
]
